<a href="https://colab.research.google.com/github/denotevn/Machine-Learning-In-ITMO/blob/main/task06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/candy-data.csv')
test = pd.read_csv('/content/sample_data/candy-test.csv')
df.head()

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0   
1   3 Musketeers          1       0        0               0       1   
2       One dime          0       0        0               0       0   
3    One quarter          0       0        0               0       0   
4      Air Heads          0       1        0               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860   
1                 0     0    1         0         0.604         0.511   
2                 0     0    0         0         0.011         0.116   
3                 0     0    0         0         0.011         0.511   
4                 0     0    0         0         0.906         0.511   

   winpercent  Y  
0   66.971725  1  
1   67.602936  1  
2   32.261086  0  
3   46.116505  0  
4   52.341465  1

In [ ]:
train = df[(df['competitorname']!='Chewey Lemonhead Fruit Mix') & \
           (df['competitorname']!='Runts') & \
           (df['competitorname']!='Sixlets')].drop(columns=['competitorname', 'Y','winpercent']).values
value = df[(df['competitorname']!='Chewey Lemonhead Fruit Mix') & \
           (df['competitorname']!='Runts') & (df['competitorname']\
                                                          !='Sixlets')]['Y'].values
pred = test.drop(columns=['competitorname', 'Y']).values
ypred = test['Y'].values

In [ ]:
train[1]

array([1.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 1.        , 0.        , 0.60399997,
       0.51099998])

In [ ]:
from sklearn.linear_model import LogisticRegression
lig  = LogisticRegression(solver= 'lbfgs',random_state=2019)
lig.fit(train,value)
#y_pred = lig.predict(x)

LogisticRegression(random_state=2019)

In [ ]:
lig.predict_proba(test[test['competitorname'] == 'Twix'].values[0][1:12].reshape(1,-1))

array([[0.60741035, 0.39258965]])

In [ ]:
lig.predict_proba(test[test['competitorname'] == 'Warheads'].values[0][1:12].reshape(1,-1))

array([[0.8504666, 0.1495334]])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(lig.predict(pred),ypred))

              precision    recall  f1-score   support

           0       0.70      0.78      0.74         9
           1       0.60      0.50      0.55         6

    accuracy                           0.67        15
   macro avg       0.65      0.64      0.64        15
weighted avg       0.66      0.67      0.66        15



In [ ]:
from sklearn.metrics import recall_score
recall_score(lig.predict(pred),ypred)

0.5

In [ ]:
from sklearn.metrics import precision_score
print(precision_score(lig.predict(pred),ypred))

0.6


In [ ]:
from sklearn.metrics import auc, roc_curve
fpr, tpr, thresholds = roc_curve(lig.predict(pred),ypred, pos_label=1)
auc(fpr, tpr)

0.638888888888889