<a href="https://colab.research.google.com/github/denotevn/Machine-Learning-In-ITMO/blob/main/task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {'X':[12,17,4,1,10,7,21,18,16,14],'Y':[26,50,9,3,25,19,53,40,26,25]}
df = pd.DataFrame(data)
df

X   Y
0  12  26
1  17  50
2   4   9
3   1   3
4  10  25
5   7  19
6  21  53
7  18  40
8  16  26
9  14  25

In [ ]:
print('mean X: ',df['X'].mean())
print('mean Y', df['Y'].mean())


mean X:  12.0
mean Y 27.6


In [ ]:
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
X = df['X'].values.reshape(-1, 1)
Y = df['Y'].values.reshape(-1, 1)
model = LinearRegression().fit(X,Y)
model.coef_



array([[2.31648936]])

In [ ]:
#theta 1
model.coef_

array([[2.31648936]])

In [ ]:
#theta0
model.intercept_

array([-0.19787234])

In [ ]:
#R^2_core
model.score(X,Y)

0.8606305383221947

Candy_data


In [ ]:
df = pd.read_csv("/content/candy-data.csv")


In [ ]:
df.head()

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0   
1   3 Musketeers          1       0        0               0       1   
2       One dime          0       0        0               0       0   
3    One quarter          0       0        0               0       0   
4      Air Heads          0       1        0               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860   
1                 0     0    1         0         0.604         0.511   
2                 0     0    0         0         0.011         0.116   
3                 0     0    0         0         0.011         0.511   
4                 0     0    0         0         0.906         0.511   

   winpercent  Y  
0   66.971725  1  
1   67.602936  1  
2   32.261086  0  
3   46.116505  0  
4   52.341465  1

In [ ]:
df.shape

(70, 14)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from pandas.core.common import random_state
import numpy as np
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
np.random.seed = 2019
X_train = df[(df['competitorname'] != 'Haribo Twin Snakes') & (df['competitorname'] != 'Hersheys Krackel')].drop(columns = ['competitorname','winpercent','Y'])
Y_train = df[(df['competitorname'] != 'Haribo Twin Snakes') & (df['competitorname'] != 'Hersheys Krackel')]['winpercent'].values 
linear.fit(X_train,Y_train)

LinearRegression()

In [ ]:
X_train.shape

(68, 11)

In [ ]:
X_test = df[df['competitorname'] == 'Haribo Twin Snakes'].drop(columns = ['competitorname','winpercent','Y'])
predict = linear.predict(X_test)
predict

array([44.64351275])

In [ ]:
X_test = df[df['competitorname'] == 'Hersheys Krackel'].drop(columns = ['competitorname','winpercent','Y'])
predict = linear.predict(X_test)
predict

array([63.86398592])

In [ ]:
res = linear.predict(np.array([0,1,1,1,0,0,1,0,0,0.32,0.219]).reshape(1,-1))
res

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([46.93601972])