<a href="https://colab.research.google.com/github/denotevn/Machine-Learning-In-ITMO/blob/main/task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

data = {'X':[96,76,98,89,87,31,73,33,87,81],'Y':[11,24,11,71,99,40,35,30,88,30],'Class':[1,1,0,0,0,0,1,0,1,1]}
df = pd.DataFrame(data = data)
df

X   Y  Class
0  96  11      1
1  76  24      1
2  98  11      0
3  89  71      0
4  87  99      0
5  31  40      0
6  73  35      1
7  33  30      0
8  87  88      1
9  81  30      1

In [ ]:
import numpy as np
X_train = np.array(df[['X','Y']])
Y_train = np.array(df['Class'])

In [ ]:
clf = KNeighborsClassifier(n_neighbors = 1, p = 2)
clf.fit(X_train,Y_train.reshape(-1,))

KNeighborsClassifier(n_neighbors=1)

In [ ]:
#1
clf.kneighbors([[68,46]],1)[0]

array([[12.08304597]])

In [ ]:
#2
clf.kneighbors([[68,46]],3)[1] + 1

array([[ 7, 10,  2]])

In [ ]:
#3
clf = KNeighborsClassifier(n_neighbors=3, p =2)
clf.fit(X_train,Y_train)
clf.predict([[68,46]])

array([1])

In [ ]:
#4
# Манхеттенское расстояние n_neighbors = 1, p = 1
clf = KNeighborsClassifier(n_neighbors=1,p=1)
clf.fit(X_train,Y_train)
clf.kneighbors([[68,46]])[0]



array([[16.]])

In [ ]:
#5
clf.kneighbors([[68,46]],3)[1] + 1

array([[ 7, 10,  2]])

In [ ]:
clf = KNeighborsClassifier(n_neighbors=3,p=1)
clf.fit(X_train,Y_train)
clf.predict([[68,46]])

array([1])